SELECT asignar_clave_jugador(2, 'Dadaismo719'); --Dario
SELECT asignar_clave_jugador(3, 'Franul194'); --Javi
SELECT asignar_clave_jugador(4, 'Frozen88Calvo#'); --Jerry
SELECT asignar_clave_jugador(5, 'SuperGata342'); --Jaime
SELECT asignar_clave_jugador(6, 'Josele183'); --Jose
SELECT asignar_clave_jugador(7, 'Mentriculo184'); --Frozen
SELECT asignar_clave_jugador(8, 'Kitos241'); --Mark
SELECT asignar_clave_jugador(9, 'Masca710'); --German
SELECT asignar_clave_jugador(10, 'Ruben962'); --Ruben
SELECT asignar_clave_jugador(11, 'Motta251'); --Mota
SELECT asignar_clave_jugador(12, 'Colocolo331'); --Antonio
SELECT asignar_clave_jugador(13, 'Momias197'); --Pablo
SELECT asignar_clave_jugador(14, 'Chudi820'); --Chudi
SELECT asignar_clave_jugador(15, 'Rixnardo'); --Rix
SELECT asignar_clave_jugador(17, 'Alonsito265'); --Alonsito
SELECT asignar_clave_jugador(29, 'MuliTercero134'); --Muli
